### ISSUE TITLE
Module list prints twice

### ISSUE THREAD

**Issue by williamsthing** [Hexeption/How-to-code-a-hacked-client-1.11#2]
[Code](http://i.imgur.com/alxlx7D.png)
[Example](http://i.imgur.com/3UXrBLc.png)

This is really bugging me out! Help would be much appreciated..

**Comment by milutinke** [comment]
Remove secound Wrapper.fr.drawString
That is causing your problem.

**Comment by williamsthing** [comment]
The issue was that I was calling the getGUI() method twice.
